services:
  # 1. The Backend Service
  - type: web
    name: psynth-backend
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 8000
      - key: ALLOWED_ORIGINS
        sync: false

  # 2. The Frontend Service
  - type: web
    name: psynth-frontend
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: psynth-backend
          property: host